[package]
name = "Simply Droplets"
version = "0.1.0"
description = "An AI powered expression sequencer"
homepage = "https://www.simply-music.ai"
author = "Simply Chris"
license = "MIT"

[dependencies]

[targets]
vst3 = { path = "target/release/simply_droplets.vst3" }
clap = { path = "target/release/simply_droplets.clap" }

[macos]
bundle_identifier = "com.simply-chris.simply-droplets"
