// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A single activity event for the UI
 */
export type ActivityEventDto = { timestamp: bigint, instance: string, channel: number, cc: number | null, value: number, note: number | null, is_note_on: boolean | null, expression_type: string | null, };
