// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActivityEventDto } from "./ActivityEventDto";

/**
 * Response containing recent MIDI activity
 */
export type ActivityResponse = { events: Array<ActivityEventDto>, };
