// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What to cancel when this fugue starts
 */
export type CancelMode = "none" | { "cancel_by_tag": string } | "cancel_all";
