// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Device } from "./Device";

/**
 * A named chain inside a container device.
 */
export type Chain = { name: string, devices: Array<Device>, };
