// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeviceTier2 } from "./DeviceTier2";

export type ChainTier2 = { name: string, devices: Array<DeviceTier2>, };
