// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Command the plugin emits to the host controller extension over
 * `/ws/controller`. No variants beyond a no-op keepalive yet; when MCP tools
 * start enqueuing real commands, add variants here without changing the
 * wire framing.
 */
export type ControllerCommand = { "type": "noop" };
