// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Command the plugin emits to the host controller extension over
 * `/ws/controller`. v1 defines no variants beyond a no-op keepalive; when
 * MCP tools start enqueuing real commands (MIDI map changes etc.), add
 * variants here without changing the wire framing.
 *
 * Serialized with `#[serde(tag = "type")]` so variants appear as
 * `{"type": "...", ...}` on the wire.
 */
export type ControllerCommand = { "type": "noop" };
