// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChainTier2 } from "./ChainTier2";
import type { DrumPadTier2 } from "./DrumPadTier2";

/**
 * Tier 2 Device — identical shape to [`Device`] but with `parameters`
 * stripped. Drum pads still recurse through this view so their inner
 * chains are visible without param clutter.
 */
export type DeviceTier2 = { "type": "instrument", name: string, vendor: string | null, preset_name: string | null, sample_name: string | null, } | { "type": "effect", name: string, vendor: string | null, preset_name: string | null, } | { "type": "drum_machine", name: string, pads: Array<DrumPadTier2>, } | { "type": "container", name: string, kind: string, chains: Array<ChainTier2>, } | { "type": "unknown", name: string, vendor: string | null, };
