// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DrumPad } from "./DrumPad";

/**
 * A device on a track's main chain. No recursion beyond drum-machine pads —
 * nested racks / chain selectors / instrument layers would require the
 * extension to walk arbitrary chain depth, which we've intentionally skipped:
 * the LLM makes all of its decisions off the primary-device summary in
 * `get_project_state`, not off deep chain detail.
 */
export type Device = { "type": "instrument", name: string, vendor: string | null, preset_name: string | null, 
/**
 * For samplers with a single loaded sample (Bitwig's Sampler,
 * Ableton's Simpler). `None` for synths.
 */
sample_name: string | null, } | { "type": "effect", name: string, vendor: string | null, preset_name: string | null, } | { "type": "drum_machine", name: string, pads: Array<DrumPad>, } | { "type": "unknown", name: string, vendor: string | null, };
