// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Chain } from "./Chain";
import type { DrumPad } from "./DrumPad";
import type { ParameterInfo } from "./ParameterInfo";

/**
 * A device somewhere in a chain. Recursive through `DrumMachine`/`Container`.
 *
 * `Unknown` is the graceful fallback for device types the host extension
 * hasn't special-cased. The LLM can still reason about "there's something
 * called X here" without breaking when new device types appear.
 */
export type Device = { "type": "instrument", name: string, vendor: string | null, preset_name: string | null, 
/**
 * For samplers with a single loaded sample (Bitwig's Sampler,
 * Ableton's Simpler). `None` for synths.
 */
sample_name: string | null, parameters: Array<ParameterInfo>, } | { "type": "effect", name: string, vendor: string | null, preset_name: string | null, parameters: Array<ParameterInfo>, } | { "type": "drum_machine", name: string, pads: Array<DrumPad>, } | { "type": "container", name: string, kind: string, chains: Array<Chain>, } | { "type": "unknown", name: string, vendor: string | null, };
