// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ParameterInfo } from "./ParameterInfo";

/**
 * Tier 3 response — just the parameter list for one addressed device.
 */
export type DeviceParameters = { device_name: string, parameters: Array<ParameterInfo>, };
