// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Device } from "./Device";

/**
 * One pad in a drum machine.
 *
 * `note` is a raw MIDI number on the wire (what the extension can easily
 * read). Outgoing serializations rendered for the LLM convert to pitch
 * notation via [`PadView`].
 */
export type DrumPad = { note: number, name: string, devices: Array<Device>, };
