// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeviceTier2 } from "./DeviceTier2";

export type DrumPadTier2 = { 
/**
 * Pitch notation, same as tier 1.
 */
note: string, name: string, devices: Array<DeviceTier2>, };
