// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response from exporting a fugue
 */
export type ExportFugueResponse = { ok: boolean, path: string | null, error: string | null, };
