// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StartMode } from "./StartMode";

/**
 * A complete fugue definition ready for playback in Droplets' sequencer.
 */
export type FugueDefinition = { 
/**
 * Unique ID for this fugue instance (serialized as string for JS compatibility)
 */
id: string, 
/**
 * Optional tag for grouping/cancellation
 */
tag: string | null, 
/**
 * Events sorted by beat_offset
 */
events: Array<import('./TimedFugueEvent').TimedFugueEvent>, 
/**
 * Total duration in beats
 */
duration_beats: number, 
/**
 * Looping behavior
 */
loop_mode: import('./LoopMode').LoopMode, 
/**
 * When to start relative to transport
 */
quantize: import('./QuantizeMode').QuantizeMode, 
/**
 * What to cancel when this starts
 */
cancel_mode: import('./CancelMode').CancelMode, 
/**
 * Interpolation mode for CC automation
 */
cc_interpolation: import('./InterpolationMode').InterpolationMode, 
/**
 * How the fugue places itself on the song-grid
 */
start_mode: StartMode, };
