// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ImportFugueResponse = { ok: boolean, 
/**
 * Freshly-assigned fugue IDs (one per imported track). Serialized as
 * strings for JS compatibility.
 */
fugue_ids: Array<string>, error: string | null, };
