// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PrimaryDevice } from "./PrimaryDevice";

export type InstanceSummary = { id: string, name: string, track_name: string | null, 
/**
 * The first instrument/drum-machine on the track's chain, or `None`
 * when no layout data is available or the chain has only effects.
 */
primary_device: PrimaryDevice | null, };
