// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PrimaryDevice } from "./PrimaryDevice";
import type { SlotHint } from "./SlotHint";

export type InstanceSummary = { id: string, name: string, track_name: string | null, 
/**
 * The track's primary sound source, or `None` when no layout data is
 * available or the track is effects-only.
 */
primary_device: PrimaryDevice | null, 
/**
 * Per-slot hints: what has the user named each of the 16 plugin slots?
 * Only non-default names are included — generic "Slot N" entries are
 * elided so the LLM isn't tempted to target unmapped slots.
 */
slots: Array<SlotHint>, };
