// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InstanceInfo } from "./InstanceInfo";

/**
 * List of available instances
 */
export type InstancesResponse = { instances: Array<InstanceInfo>, };
