// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PrimaryDevice } from "./PrimaryDevice";

export type InstanceSummary = { id: string, name: string, track_name: string | null, 
/**
 * The track's primary sound source, or `None` when no layout data is
 * available or the track is effects-only.
 */
primary_device: PrimaryDevice | null, };
