// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Interpolation mode for continuous-signal ramps (CC, per-note expression).
 *
 * New curves extend this enum and add one line to [`InterpolationMode::apply_curve`];
 * every interpolator site routes through that function so new variants propagate
 * automatically to CC audio-thread ramps and per-note server-side expansion.
 */
export type InterpolationMode = "none" | "linear" | "exp" | "log";
