// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Interpolation mode for CC automation
 */
export type InterpolationMode = "none" | "linear";
