// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Tier 1 view of a drum pad — just what the LLM needs to pick the right
 * note. Note rendered as DAW pitch notation (`"C1"`, C3=60) not an integer.
 */
export type PadSummary = { 
/**
 * Pitch notation — `"C1"`, `"F#2"` (DAW convention, C3=60). Comes from converting the raw MIDI
 * number in [`DrumPad::note`].
 */
note: string, name: string, 
/**
 * If a single sampler is loaded on the pad, its sample file name.
 * Surfaced at tier 1 because the whole point of tier 1 for drums is
 * "which sample sits on which note."
 */
sample_name: string | null, };
