// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One pad on a drum machine. Stored as a raw MIDI note; serializes out as
 * DAW pitch notation (`"C1"`, C3=60) so MCP consumers (LLMs) and the frontend
 * read the same format they use for fugue notes. The controller extension
 * posts the integer directly — a single canonical midi→name formula lives
 * in `midi_to_name`, so the extension can't drift from the plugin's convention.
 */
export type PadSummary = { note: string, name: string, 
/**
 * Preset / sample name surfaced from the pad's nested instrument when
 * available. For Bitwig's Sampler this is the loaded audio file name,
 * so the LLM sees `kick_808.wav` next to `C1 — Kick`.
 */
sample_name: string | null, };
