// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One pad on a drum machine. `note` is DAW pitch notation (`"C1"`, C3=60)
 * — the extension renders it so the LLM reads the same format it already
 * uses in fugue notes.
 */
export type PadSummary = { note: string, name: string, 
/**
 * Preset / sample name surfaced from the pad's nested instrument when
 * available. For Bitwig's Sampler this is the loaded audio file name,
 * so the LLM sees `kick_808.wav` next to `C1 — Kick`.
 */
sample_name: string | null, };
