// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Parameter info for tier 3 (`get_device_parameters`).
 *
 * Kept separate from the always-present Device fields so Tier 1/2 views can
 * skip them without an explicit schema change. The extension may still
 * populate `parameters` on every device — we just hide them in the tier 1/2
 * wrappers.
 */
export type ParameterInfo = { name: string, index: number, displayed_value: string | null, };
