// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PadSummary } from "./PadSummary";

/**
 * The track's primary sound source. Either a single instrument (synth or
 * sampler) or a drum machine whose pads we enumerate so the LLM can target
 * the right MIDI note for each sound.
 */
export type PrimaryDevice = { "type": "instrument", name: string, vendor: string | null, preset_name: string | null, } | { "type": "drum_machine", name: string, pads: Array<PadSummary>, };
