// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PadSummary } from "./PadSummary";

/**
 * A compact view of the track's primary sound source for tier 1.
 * Drum machines include pad summaries because "what's on each pad" is
 * precisely the reason tier 1 exists for drum tracks.
 */
export type PrimaryDevice = { "type": "instrument", name: string, vendor: string | null, preset_name: string | null, sample_name: string | null, } | { "type": "drum_machine", name: string, pads: Array<PadSummary>, };
