// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InstanceSummary } from "./InstanceSummary";
import type { OtherTrackSummary } from "./OtherTrackSummary";

/**
 * Result of `get_project_state`. Instances listed in registration order.
 * `other_tracks` covers tracks without a Droplets device, so the LLM has
 * full project context even for tracks it can't directly play.
 */
export type ProjectState = { instances: Array<InstanceSummary>, other_tracks: Array<OtherTrackSummary>, 
/**
 * True when a host controller extension has pushed a layout; false when
 * the LLM should fall back to asking the user / using GM conventions.
 */
layout_available: boolean, 
/**
 * User-authored context from the Settings tab. Piped through here so
 * LLMs see the latest content on every `get_project_state` call —
 * MCP's initialize-time instructions are baked once per session and
 * don't pick up edits the user makes mid-conversation. Skipped from
 * the wire when empty so the common "nothing configured" case adds
 * zero bytes to the response.
 */
custom_instructions: string, };
