// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TrackContext } from "./TrackContext";

/**
 * Project-wide snapshot pushed by the host controller extension.
 *
 * Keyed by track name. Tracks without a Droplets device are included too —
 * the LLM benefits from seeing the full project context ("there's a Vocals
 * track I can't play, but the user may ask about it").
 */
export type ProjectLayout = { tracks: Array<TrackContext>, };
