// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InstanceSummary } from "./InstanceSummary";
import type { OtherTrackSummary } from "./OtherTrackSummary";

/**
 * Result of `get_project_state`. Instances listed in registration order.
 * `other_tracks` covers tracks without a Droplets device, so the LLM has
 * full project context even for tracks it can't directly play.
 */
export type ProjectState = { instances: Array<InstanceSummary>, other_tracks: Array<OtherTrackSummary>, 
/**
 * True when a host controller extension has pushed a layout; false when
 * the LLM should fall back to asking the user / using GM conventions.
 */
layout_available: boolean, };
