// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * When to start a fugue relative to transport position
 */
export type QuantizeMode = "Immediate" | "NextBeat" | "NextBar" | { "NextBars": number };
