// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Quantization interval for fugue playback
 *
 * Defines a grid that the fugue aligns to. The fugue will start when the
 * transport reaches a grid line (where current_beat % interval == 0).
 * Beat 0 is always a valid grid line for all intervals.
 */
export type QuantizeMode = "immediate" | "beat" | "bar" | { "bars": number };
