// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One parameter on the primary instrument's Remote Controls Page 1.
 */
export type RemoteControlInfo = { index: number, name: string, };
