// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SlotInfo } from "./SlotInfo";

/**
 * Response containing all CC slots
 */
export type SlotsResponse = { slots: Array<SlotInfo>, };
