// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One slot's name hint for the LLM. `cc` lists the slot's backing MIDI CC
 * number, kept for parity with the standalone hardware path — for host-param
 * automation in a DAW, the LLM should use a `slot` fugue lane keyed by
 * `index`, not emit raw CC.
 */
export type SlotHint = { index: number, name: string, cc: number | null, };
