// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How a promoted fugue places itself on the song-grid when its quantize
 * target isn't already aligned to its `duration_beats`.
 *
 * Iteration boundaries always live at `k · duration_beats` from song-beat-0
 * regardless of this mode — that's the "queue-time latency can't shift
 * musical alignment" invariant. This mode only decides what happens
 * *between* the queue moment and the next iteration boundary.
 */
export type StartMode = "phase" | "boundary";
