// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How a promoted fugue places itself on the song-grid when its quantize
 * target isn't already aligned to its `duration_beats`.
 */
export type StartMode = "phase" | "boundary";
