// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FugueEvent } from "./FugueEvent";

/**
 * A fugue event with timing information
 */
export type TimedFugueEvent = { 
/**
 * Beat offset relative to fugue start (0.0 = start of fugue)
 */
beat_offset: number, 
/**
 * The event to trigger
 */
event: FugueEvent, };
