// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Device } from "./Device";
import type { RemoteControlInfo } from "./RemoteControlInfo";

/**
 * One track's worth of context.
 */
export type TrackContext = { track_name: string, 
/**
 * Instance ID of the Droplets device on this track, if any.
 */
droplets_instance_id: string | null, devices: Array<Device>, 
/**
 * Primary-instrument Remote Controls Page 1, as seen by the host controller
 * extension. Only populated when a Droplets instance is on this track.
 * Each entry describes one of the 8 remote-control parameters by index and
 * human-readable name — the plugin mirrors these onto slots 0–7 so the LLM
 * can automate named instrument parameters without the user hand-mapping.
 */
remote_controls: Array<RemoteControlInfo>, };
