// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Device } from "./Device";

/**
 * One track's worth of context.
 */
export type TrackContext = { track_name: string, 
/**
 * Instance ID of the Droplets device on this track, if any.
 */
droplets_instance_id: string | null, devices: Array<Device>, };
