// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeviceTier2 } from "./DeviceTier2";

/**
 * Tier 2 view of one track. Mirrors [`TrackContext`] but drops `parameters`
 * on every device via [`DeviceTier2`].
 */
export type TrackInfo = { track_name: string, droplets_instance_id: string | null, devices: Array<DeviceTier2>, };
