// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PrimaryDevice } from "./PrimaryDevice";
import type { RemoteControlInfo } from "./RemoteControlInfo";

/**
 * One track's worth of context. The extension picks the track's primary
 * sound source (first instrument on the chain, or a drum machine) and
 * encodes only that — nested racks, chain selectors, effects aren't
 * surfaced because the LLM never actually used them.
 */
export type TrackContext = { track_name: string, 
/**
 * Instance ID of the Droplets device on this track, if any.
 */
droplets_instance_id: string | null, 
/**
 * Primary sound source on this track, or `None` for effects-only tracks.
 */
primary_device: PrimaryDevice | null, 
/**
 * Primary-instrument Remote Controls Page 1, as seen by the host controller
 * extension. Only populated when a Droplets instance is on this track.
 * Each entry describes one of the 8 remote-control parameters by index and
 * human-readable name — a hint the plugin/UI can use for slot naming.
 */
remote_controls: Array<RemoteControlInfo>, };
