// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TransportState } from "./TransportState";

/**
 * Response containing transport state
 */
export type TransportResponse = { transport: TransportState, };
