// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CancelMode } from "./CancelMode";
import type { InterpolationMode } from "./InterpolationMode";
import type { LoopMode } from "./LoopMode";
import type { QuantizeMode } from "./QuantizeMode";
import type { TimedFugueEvent } from "./TimedFugueEvent";

/**
 * A complete fugue definition ready for playback
 */
export type FugueDefinition = { 
/**
 * Unique ID for this fugue instance (serialized as string for JS compatibility)
 */
id: string, 
/**
 * Optional tag for grouping/cancellation
 */
tag: string | null, 
/**
 * Events sorted by beat_offset
 */
events: Array<TimedFugueEvent>, 
/**
 * Total duration in beats
 */
duration_beats: number, 
/**
 * Looping behavior
 */
loop_mode: LoopMode, 
/**
 * When to start relative to transport
 */
quantize: QuantizeMode, 
/**
 * What to cancel when this starts
 */
cancel_mode: CancelMode, 
/**
 * Interpolation mode for CC automation
 */
cc_interpolation: InterpolationMode, };
