// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FugueDefinition } from "./FugueDefinition";

/**
 * Response for a single fugue definition
 */
export type FugueResponse = { fugue: FugueDefinition | null, };
