// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Information about an active fugue for listing
 */
export type FugueInfo = { id: bigint, tag: string | null, current_loop: number, total_loops: number | null, is_waiting: boolean, progress_beats: number, duration_beats: number, 
/**
 * Absolute beat when this fugue started (for UI position calculation)
 */
start_beat: number, 
/**
 * Quantization interval in beats (for UI playhead: transport_beat % interval)
 * None means Immediate mode (no grid alignment)
 */
quantize_interval_beats: number | null, };
