// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InterpolationMode } from "./InterpolationMode";

/**
 * A single musical event in a fugue
 */
export type FugueEvent = { "type": "note_on", channel: number, note: number, velocity: number, } | { "type": "note_off", channel: number, note: number, } | { "type": "cc", channel: number, cc: number, value: number, curve: InterpolationMode | null, } | { "type": "per_note_pitch_bend", channel: number, note: number, 
/**
 * Pitch bend in semitones (-64.0 to +64.0)
 */
semitones: number, } | { "type": "per_note_pressure", channel: number, note: number, 
/**
 * Pressure value 0.0-1.0
 */
pressure: number, };
