// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * API response type for settings
 */
export type SettingsResponse = { export_path: string, mcp_port: number, mcp_url: string, };
