// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Slot info for API serialization
 */
export type SlotInfo = { index: number, name: string, cc: number | null, channel: number, value: number, learning: boolean, };
