// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Transport state for UI synchronization
 */
export type TransportState = { 
/**
 * Current beat position in the song
 */
beat: number, 
/**
 * Current tempo in BPM
 */
tempo: number, 
/**
 * Whether playback is active
 */
playing: boolean, 
/**
 * Time signature numerator (beats per bar)
 */
time_sig_numerator: number, };
