// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Transport state for UI synchronization
 */
export type TransportState = { 
/**
 * Current beat position in the song
 */
beat: number, 
/**
 * Current tempo in BPM
 */
tempo: number, 
/**
 * Whether playback is active
 */
playing: boolean, 
/**
 * Time signature numerator (beats per bar)
 */
time_sig_numerator: number, 
/**
 * Whether DAW loop is active
 */
is_looping: boolean, 
/**
 * Loop start beat (only valid if is_looping is true)
 */
loop_start_beat: number, 
/**
 * Loop end beat (only valid if is_looping is true)
 */
loop_end_beat: number, };
